max_length_name: 50
max_length_email: 250
min_length_password: 6
valid_email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
gravatar:
  size: 50
valid_number_regex: \A\d+\z
pagy:
  page_count_10: 10
digits:
  digit_140: 140
link:
  rails_home: http://www.railstutorial.org/
image:
  max_size: 5
  content_type: <%= %w(image/jpeg image/gif image/png) %>
  resize_to_limit: [200, 100]
  valid: image/jpeg,image/gif,image/png
